import asyncio  # Used to run async event loop
from langchain_core.messages import HumanMessage  # Standard message format for LLM input
from .graph import build_graph  # Builds the agent execution graph/workflow
from .lsp_tools import init_lsp, lsp_client  # LSP initialization + client reference
import src.agents.coding_agent.lsp_tools as lsp_tools  # Import full module to access updated global state


async def run_agent(request: str, working_dir: str):
    """
    Runs the coding agent workflow asynchronously.

    This function:
    1. Initializes the Language Server Protocol (LSP) for the given working directory
    2. Builds the execution graph (agent workflow)
    3. Sends a request (task) to the agent
    4. Prints the generated plan and review results
    5. Ensures proper cleanup of LSP resources

    Args:
        request (str):
            The task or instruction given to the agent.
            Example: "Add input validation to login function"

        working_dir (str):
            Path to the directory where the agent operates.
            This typically contains the codebase being analyzed or modified.

    Notes:
        - Uses async execution because LangGraph agents are asynchronous
        - Ensures LSP is always shut down (even if execution fails)
        - Maintains internal agent state such as plan, iterations, and review status
    """

    # Initialize LSP (Language Server Protocol) for code intelligence (e.g., autocomplete, diagnostics)
    init_lsp(working_dir)

    # Build the agent workflow graph (planner → executor → reviewer, etc.)
    app = build_graph(working_dir)

    try:
        # Invoke the agent asynchronously with initial state
        result = await app.ainvoke({
            # Input message to the LLM agent
            "messages": [HumanMessage(content=request)],

            # Context: working directory where code operations happen
            "working_dir": working_dir,

            # Iteration counters for controlling agent loops
            "planner_iterations": 0,
            "executor_iterations": 0,

            # Plan generated by planner (initially None)
            "plan": None,

            # Tracks file modifications made during execution
            "file_changes": [],

            # Review system state
            "review_status": "pending",   # can become approved / rejected
            "review_feedback": "",       # reviewer comments

            # Number of times revisions were attempted
            "revision_count": 0
        })

        # Output the generated execution plan
        print("=== PLAN ===")
        print(result["plan"])

        # Output review results from the agent
        print("\n=== REVIEW STATUS ===")
        print(result["review_status"])
        print(result["review_feedback"])

    finally:
        # Access via module so you get the updated reference, not the None snapshot
        """use lsp_tools.lsp_client instead of lsp_client — when you do from lsp_tools import lsp_client you get a snapshot of None at import time.
        Accessing it via the module always gives you the current value after init_lsp() has set it."""

        # Ensure LSP client is properly shut down to avoid resource leaks
        if lsp_tools.lsp_client is not None:
            lsp_tools.lsp_client.shutdown()


# Entry point: runs the async agent
asyncio.run(run_agent(
    # Example tasks (commented for quick switching during testing)
    # request="Add input validation to the login function in auth/login.py",
    # request="List all end points in llm_endpoint.py",

    # Active request
    request="add suport for anthropic model. Also update logging module to only display CRITICAL logs",

    # Directory containing the target codebase
    working_dir="/home/wahaj/study/agentic-sdlc/output/3"
))