import os, shutil, json  # OS operations, file handling, JSON parsing
import subprocess  # Used for running external commands (e.g., linters)
from typing_extensions import TypedDict, Optional, List, Literal, Dict, Any
from typing import Annotated
from langchain_openai import ChatOpenAI  # LLM interface
from langchain_core.prompts import ChatPromptTemplate  # Prompt builder
from langchain_core.output_parsers import PydanticOutputParser  # Structured output parsing
from langgraph.graph import StateGraph, END  # Graph-based workflow engine
from langgraph.graph.message import add_messages  # Message reducer utility
from langgraph.types import Send  # Used for parallel execution (fan-out)
from pydantic import BaseModel, Field  # Data validation + schema definition
from dotenv import load_dotenv  # Load environment variables
from src.tools.read_file_structure import read_file_structure  # Custom tool: directory structure
from src.tools.read_file import read_file  # Custom tool: file reading
from src.config.logging_config import logger  # Central logging system


# Load environment variables from .env file
load_dotenv()

# Base working directory where all executions will happen
working_dir = os.getenv("WORKING_DIR")

# Maximum retry attempts for reviewer loop
MAX_REVIEW_RETRIES = int(os.getenv("MAX_REVIEW_RETRIES", 3))

# Maximum retry attempts for static analysis loop
MAX_STATIC_CHECK_RETRIES = int(os.getenv("MAX_STATIC_CHECK_RETRIES", 3))


# Initialize LLM (local inference server)
llm = ChatOpenAI(
    base_url="http://localhost:8080/v1",  # Local LLM endpoint
    # model="Qwen2.5-7B-Instruct.Q4_0.gguf",  # Alternative model (commented)
    model="Qwen2.5-Coder-7B-Instruct.Q4_0.gguf",  # Code-specialized model
    api_key="not_needed",  # No API key required for local server
    # callbacks=[SimpleLogger()]  # Optional logging callbacks
)


def append_list(existing, new):
    """
    Reducer that accumulates list results from parallel subgraphs.

    This function is used in conjunction with LangGraph's `Annotated`
    fields to merge outputs from multiple parallel executions.

    Parameters:
        existing (list | None):
            Previously accumulated list of values.

        new (list | None):
            Newly returned list of values from a node/subgraph.

    Returns:
        list:
            Combined list containing both existing and new values.

    Behavior:
        - Handles None values safely
        - Ensures lists are concatenated instead of overwritten

    Notes:
        - Critical for fan-out/fan-in workflows
        - Used for aggregating results like `code_changes`, `written_files`
    """

    # If either is None, replace with empty list before concatenation
    return (existing or []) + (new or [])


class AgentState(TypedDict):
    """
    Global state object shared across all nodes in the workflow.

    This state is passed between nodes in the LangGraph execution pipeline
    and gets incrementally updated as the workflow progresses.

    Fields:
        execution_id (int):
            Unique identifier for the current execution run.

        work_dir (str):
            Absolute path to the working directory for this execution.

        task (str):
            User-provided task description.

        file_structure (str):
            Snapshot of the repository structure (tree format).

        existing_files (Optional[Dict[str, str]]):
            Mapping of file path → file content (used for updates).

        plan (Optional[Dict[str, Any]]):
            Structured plan generated by the planner node.

        code_changes (Annotated):
            Aggregated list of code changes across all files.
            Uses `append_list` reducer to merge results.

        written_files (Annotated):
            List of file paths written to disk.
            Uses `append_list` reducer.

        review (Optional[Dict[str, str]]):
            Reviewer output (status, issues, suggestions).

        static_check_success (Optional[bool]):
            Whether static analysis passed.

        static_check_output (Optional[str]):
            Raw output from static analysis tool.

        feedback (Optional[str]):
            Feedback passed back into retry loops.

        retry_count (Dict[str, int]):
            Tracks retry attempts for different stages:
                - review
                - static_check_count
    """

    execution_id: int
    work_dir: str
    task: str
    file_structure: str
    existing_files: Optional[Dict[str, str]]  # path -> content
    plan: Optional[Dict[str, Any]]

    # Annotated with reducer to merge parallel results
    code_changes: Annotated[Optional[Dict[str, Any]], append_list]
    written_files: Annotated[Optional[List[str]], append_list]

    review: Optional[Dict[str, str]]
    static_check_success: Optional[bool]
    static_check_output: Optional[str]
    feedback: Optional[str]
    retry_count: Dict[str, int]


def setup_node(state: AgentState):
    """
    Initialize execution environment and state.

    Parameters:
        state (AgentState):
            Initial state containing at least the task.

    Returns:
        AgentState:
            Updated state with:
                - execution_id
                - work_dir
                - retry_count initialized

    Behavior:
        - Assigns execution ID (currently hardcoded)
        - Constructs working directory path
        - Initializes retry counters for workflow loops

    Notes:
        - execution_id should ideally come from a database or job queue
        - working_dir isolates each execution to avoid conflicts
    """

    logger.info("*"*20)
    logger.info("Executing Setup Node")
    # To do : last execution id will be fetch from the databse and +1 will be used as next
    state["execution_id"] = 3 # hard coded temporarily 
    state["work_dir"] = os.path.join(working_dir, str(state["execution_id"]))

    # Initialize retry counters for loops
    state["retry_count"] = {"review": 0, "static_check_count": 0}

    return state


def file_structure_node(state: AgentState):
    """
    Read and store the repository file structure.

    Parameters:
        state (AgentState):
            Must contain "work_dir"

    Returns:
        dict:
            {"file_structure": str}

    Behavior:
        - Calls read_file_structure tool
        - Stores directory tree for planner context

    Notes:
        - Provides high-level visibility of project layout
        - Used by planner to decide which files to modify
    """

    logger.info("Reading File Strucutre")

    # Read directory structure (tree-like format)
    structure = read_file_structure.invoke(state["work_dir"])

    # Store in state
    state["file_structure"] = structure

    logger.debug(f"Updating File Structure: \n{structure}")

    return {"file_structure": state["file_structure"]}


class FilePlan(BaseModel):
    """
    Represents a single file operation in the execution plan.

    Fields:
        path (str):
            Absolute file path (must be inside working_dir).

        action (Literal["create", "update"]):
            Type of operation:
                - "create": new file
                - "update": modify existing file

        reason (str):
            Explanation of why this file needs modification.
    """

    path: str = Field(description="This is an absolute path of file where work_dir is the parent directory.")
    action: Literal["create", "update"]
    reason: str


class Plan(BaseModel):
    """
    Represents the full execution plan generated by the planner.

    Fields:
        summary (str):
            High-level description of the task and approach.

        files (List[FilePlan]):
            List of file-level operations to perform.
    """

    summary: str
    files: List[FilePlan]


# Parser to convert LLM output into structured Plan object
parser = PydanticOutputParser(pydantic_object=Plan)


# Prompt template for planner node
planner_prompt = ChatPromptTemplate.from_messages([
    ("system", """
You are a senior software architect.

Your job is to create a precise implementation plan.

Rules:
- Prefer updating existing files over creating new ones.
- Only create new files if necessary.
- Respect the apparent project structure.
- Keep modifications minimal and modular.
- Return structured JSON only.
"""),
    ("user", """
Task:
{task}

Working Directory:
{work_dir}

Repository file structure:
{file_structure}

{format_instructions}
""")
])



def planner_node(state: AgentState):
    """
    Generate a structured execution plan using the LLM.

    Parameters:
        state (AgentState):
            Current workflow state containing:
                - task (str): user request
                - work_dir (str): execution directory
                - file_structure (str): project layout

    Returns:
        dict:
            {
                "plan": dict  # serialized Plan model
            }

    Behavior:
        - Formats prompt using task, working directory, and file structure
        - Sends prompt to LLM with structured output parsing
        - Converts result into dictionary format for downstream nodes

    Notes:
        - Uses PydanticOutputParser for strict JSON schema enforcement
        - Avoids manual JSON parsing (safer and more reliable)
        - Does NOT mutate state directly — returns delta instead
    """

    logger.info("Executing Planner Node")

    # Build prompt with dynamic context
    formatted_prompt = planner_prompt.format_messages(
        task=state["task"],  # user input task
        work_dir=state["work_dir"],  # execution directory
        file_structure=state["file_structure"],  # repo structure
        format_instructions=parser.get_format_instructions()  # JSON schema instructions
    )

    logger.debug(f"Python Planner Prompt: \n{formatted_prompt}")

    # OLD approach (manual parsing)
    # response = llm.invoke(formatted_prompt)
    # plan = parser.parse(response.content)

    # NEW approach: enforce structured output via Pydantic model
    plan = llm.with_structured_output(Plan).invoke(formatted_prompt)

    # Return serialized plan (not mutating original state)
    return {"plan": plan.model_dump()}


def reader_node(state: AgentState):
    """
    Read contents of files that need to be updated.

    Parameters:
        state (AgentState):
            Must contain:
                - plan (dict): output from planner

    Returns:
        AgentState:
            Updated state with:
                - existing_files (dict[path → content])

    Behavior:
        - Extracts files marked with action="update"
        - Reads file contents using read_file tool
        - Stores results in state["existing_files"]

    Notes:
        - Only reads files that will be modified
        - Skips "create" files (since they don't exist yet)
    """

    logger.info("Executing Reader Node")

    plan = state["plan"]

    # Extract only files that need updates
    files_to_update = [
        file["path"] for file in plan["files"]  # ignore type-check
        if file["action"] == "update"
    ]

    existing_files = {}

    # Read each file's content
    for path in files_to_update:
        content = read_file.invoke(path)
        existing_files[path] = content  # store path → content mapping

    # Store in state
    state["existing_files"] = existing_files

    logger.debug(f"Existing Files: \n{existing_files}")

    return state


def should_read(state: AgentState) -> Literal["reader", "skip_reader"]:
    """
    Decide whether the reader node should be executed.

    Parameters:
        state (AgentState):
            Must contain plan

    Returns:
        Literal["reader", "skip_reader"]:
            - "reader": if any file requires update
            - "skip_reader": if only new files are created

    Behavior:
        - Iterates through planned files
        - Checks if any file has action="update"
        - Handles exceptions safely

    Notes:
        - Prevents unnecessary file reads
        - Improves performance when only creating new files
    """

    plan = state["plan"]

    try:
        # Check if any file needs updating
        for file in plan["files"]:
            if file["action"] == "update":
                return "reader"

        # No updates → skip reader
        return "skip_reader"

    except FileNotFoundError:
        # If plan structure is invalid or missing
        return "skip_reader"

    except Exception as e:
        print(f"Error occured: {e}")
        return "skip_reader"


# skip_reader is a passthrough node that just returns state
def skip_reader_node(state: AgentState):
    """
    Passthrough node that skips file reading.

    Parameters:
        state (AgentState)

    Returns:
        AgentState:
            Unmodified state

    Behavior:
        - Used when no files need reading
        - Acts as a no-op node in the graph

    Notes:
        - Helps maintain consistent graph structure
        - Avoids conditional branching complexity
    """
    return state


class CodeChange(BaseModel):
    """
    Represents a single file change operation.

    Fields:
        path (str):
            Absolute file path (must be inside working directory)

        action (Literal["create", "update"]):
            Type of operation:
                - "create": new file
                - "update": modify existing file

        content (str):
            Full file content after modification

    Notes:
        - Current design uses full-file overwrite (v1)
        - Future improvement: support diff/patch-based updates (v2)
    """

    path: str = Field(description="This is an absolute path of file  where work_dir is the parent directory.")
    action: Literal["create", "update"]
    content: str  # full new content (safe v1 design)


class CodeOutput(BaseModel):
    """
    Represents output for multi-file code generation.

    Fields:
        summary (str):
            High-level description of changes made

        changes (List[CodeChange]):
            List of file modifications
    """

    summary: str
    changes: List[CodeChange]


class SingleFileOutput(BaseModel):
    """
    Represents output for single-file code generation.

    Fields:
        summary (str):
            Description of changes made to the file

        change (CodeChange):
            Single file modification
    """

    summary: str
    change: CodeChange


class FileAgentState(TypedDict):
    """
    State used for per-file execution in subgraph.

    This state isolates execution for a single file,
    enabling parallel or sequential processing.

    Fields:

    Inherited context:
        execution_id (int): execution identifier
        work_dir (str): working directory
        task (str): original user task
        feedback (Optional[str]): feedback from previous iterations
        retry_count (Dict[str, int]): retry tracking
        written_files (Annotated): files written so far

    Per-file fields:
        file_plan (FilePlan): plan for this specific file
        existing_file_content (Optional[str]): content for updates
        code_change (Optional[CodeChange]): generated change
        review (Optional[Dict]): review result
        code_changes (Annotated): aggregated changes
        static_check_success (Optional[bool]): lint success
        static_check_output (Optional[str]): lint logs

    Notes:
        - Designed for subgraph execution
        - Supports fan-out/fan-in architecture
        - Keeps file-level processing isolated
    """

    # Inherited context
    execution_id: int
    work_dir: str
    task: str
    feedback: Optional[str]
    retry_count: Dict[str, int]

    # Aggregated outputs (with reducer)
    written_files: Annotated[Optional[List[str]], append_list]

    # Per-file fields
    file_plan: FilePlan  # single FilePlan (not a list)
    existing_file_content: Optional[str]  # file content for updates
    code_change: Optional[CodeChange]  # generated change
    review: Optional[Dict[str, str]]

    # Aggregated across subgraph
    code_changes: Annotated[Optional[Dict[str, Any]], append_list]

    # Static analysis results
    static_check_success: Optional[bool]
    static_check_output: Optional[str]


def fan_out_node(state: AgentState) -> List[Send]:
    """Dispatch one subgraph execution per file in the plan."""

    """
    Create parallel execution tasks (fan-out) for each file in the plan.

    Parameters:
        state (AgentState):
            Must contain:
                - plan["files"]: list of FilePlan objects
                - execution metadata (execution_id, work_dir, etc.)

    Returns:
        List[Send]:
            List of Send objects, each triggering a subgraph execution.

    Behavior:
        - Iterates through all files in the plan
        - Creates a separate FileAgentState for each file
        - Passes file-specific context into subgraph
        - Enables parallel or independent execution

    Notes:
        - This is a classic "fan-out" pattern in LangGraph
        - Each file is processed independently in the subgraph
        - Helps scale multi-file operations efficiently
    """

    sends = []

    # Iterate through each file in the execution plan
    for file_plan in state["plan"]["files"]:

        # Default: no existing content
        existing_content = None

        # If file is being updated, fetch existing content
        if file_plan["action"] == "update":
            existing_content = state.get("existing_files", {}).get(file_plan["path"])

        # Create a Send object to trigger subgraph execution
        sends.append(Send(
            "file_subgraph",  # target node (subgraph)
            FileAgentState(
                execution_id=state["execution_id"],  # execution context
                work_dir=state["work_dir"],  # working directory
                task=state["task"],  # user task
                feedback=state.get("feedback"),  # feedback from previous loop
                retry_count=state.get("retry_count"),  # retry tracking
                written_files=state.get("written_files"),  # accumulated outputs

                # File-specific context
                file_plan=file_plan,
                existing_file_content=existing_content,

                # Initialize per-file state
                code_change=None,
                review=None,
            )
        ))

    return sends


def fan_out_edges(state: AgentState) -> List[Send]:
    """
    Alternative fan-out implementation using dictionary-based state.

    Parameters:
        state (AgentState)

    Returns:
        List[Send]:
            Send objects for subgraph execution

    Behavior:
        - Uses list comprehension instead of loop
        - Constructs state as dictionary instead of TypedDict instance
        - Functionally equivalent to fan_out_node

    Notes:
        - Often used in conditional edges in LangGraph
        - More concise but slightly less explicit than fan_out_node
    """

    return [
        Send(
            "file_subgraph",
            {
                "execution_id": state["execution_id"],
                "work_dir": state["work_dir"],
                "task": state["task"],
                "feedback": state.get("feedback"),
                "retry_count": state.get("retry_count"),
                "written_files": state.get("written_files"),

                # Current file plan
                "file_plan": file_plan,

                # Only include content if updating
                "existing_file_content": (
                    (state.get("existing_files") or {}).get(file_plan["path"])
                    if file_plan["action"] == "update"
                    else None
                ),

                # Initialize execution state
                "code_change": None,
                "review": None,
            }
        )
        for file_plan in state["plan"]["files"]
    ]


# Parser for multi-file output
coder_parser = PydanticOutputParser(pydantic_object=CodeOutput)

# Parser for single-file output (used in subgraph)
file_coder_parser = PydanticOutputParser(pydantic_object=SingleFileOutput)


# Prompt template for code generation
coder_prompt = ChatPromptTemplate.from_messages([
    ("system", """
You are a senior software engineer.

Your job:
Generate precise code changes based on the plan.

Rules:
- For "create" → produce complete new file.
- For "update" → modify existing file carefully.
- Preserve unrelated logic.
- Do NOT remove functionality unless required.
- Keep changes minimal and clean.
- Maintain style consistency.
- Return structured JSON only.
"""),
    ("user", """
Task:
{task}

Implementation Plan:
{plan}

Static Analysis Feedback (if any):
{feedback}

Existing Files (only for updates):
{existing_files}

Format Instructions:
{format_instructions}
""")
])


from langgraph.types import RetryPolicy


def coder_node(state: FileAgentState):
    """
    Generate code changes for a single file using LLM.

    Parameters:
        state (FileAgentState):
            Contains:
                - task (str)
                - file_plan (FilePlan)
                - existing_file_content (str | None)
                - feedback (optional retry feedback)

    Returns:
        FileAgentState:
            Updated state with:
                - code_change (dict)

    Behavior:
        - Formats prompt using task + file-specific plan
        - Calls LLM with structured output schema
        - Generates full file content (v1 design)
        - Handles errors and logs failures

    Notes:
        - Uses SingleFileOutput schema (one file at a time)
        - Safer than free-text generation (strict schema)
        - Future upgrade: diff/patch-based generation (v2)
    """

    logger.info("Executing Coder Node")

    # Build prompt with file-specific context
    formatted_prompt = coder_prompt.format_messages(
        task=state["task"],  # user task
        plan=state["file_plan"],  # file-specific plan
        feedback=state.get("feedback", ""),  # retry feedback (if any)
        existing_files=state.get("existing_file_content", {}),  # existing content
        format_instructions=file_coder_parser.get_format_instructions()  # schema instructions
    )

    # OLD approach:
    # response = llm.invoke(formatted_prompt)

    # NEW: enforce structured output via Pydantic
    llm_structured = llm.with_structured_output(SingleFileOutput)

    try:
        # Invoke LLM
        code_output = llm_structured.invoke(formatted_prompt)

        # OLD parsing:
        # code_output = coder_parser.parse(response.content)

    except Exception as e:
        # Log failure with file context
        logger.error(f"Coder failed for {state['file_plan']['path']}: {e}")
        raise e

    # Log generated code
    logger.debug(f"Generated CODE: \n {code_output.model_dump()}")

    # Return updated state (do not mutate original directly)
    return {
        **state,
        "code_change": code_output.change.model_dump()
    }


def fan_in_node(state: AgentState):
    """Collect all per-file code_changes back into the main state."""

    """
    Aggregate results from all subgraph executions (fan-in).

    Parameters:
        state (AgentState):
            Contains aggregated results from subgraphs

    Returns:
        AgentState:
            Final merged state

    Behavior:
        - Collects results from all file-level executions
        - Uses reducers (append_list) to merge results automatically
        - Logs number of processed files

    Notes:
        - This is the "fan-in" counterpart of fan-out
        - No manual aggregation needed due to reducers
        - Final state contains all file changes
    """

    # OLD manual aggregation (commented out)
    # all_changes = [
    #     result["code_change"] for result in subgraph_results
    #     if result.get("code_change") is not None
    # ]

    # Log aggregated results
    logger.info(f"Fan-in received {len(state.get('code_changes', []))} file results")

    return state

class ReviewResult(BaseModel):
    """
    Represents the structured output of the reviewer LLM.

    Fields:
        status (Literal["approved", "needs_revision"]):
            Final decision of the reviewer:
                - "approved": changes are acceptable
                - "needs_revision": changes require fixes

        issues (List[str]):
            List of identified problems in the proposed code:
                - Missing imports
                - Logical errors
                - Architectural issues
                - Style violations

        suggestion (List[str]):
            Actionable suggestions for improving the code:
                - Fixes for issues
                - Recommended refactors
                - Improvements for clarity or performance

        confidence (float):
            Confidence score (0.0 → 1.0) indicating how certain
            the reviewer is about its decision.

    Notes:
        - This schema enforces structured evaluation output
        - Enables automated decision-making in workflow
    """

    status: Literal["approved", "needs_revision"]
    issues: List[str]
    suggestion: List[str]
    confidence: float = Field(description="The value must be between 0.0 - 1.0")


# Parser to convert LLM output → ReviewResult model
reviewer_parser = PydanticOutputParser(pydantic_object=ReviewResult)


# Prompt template for reviewer LLM
reviewer_prompt = ChatPromptTemplate.from_messages([
    ("system", """
You are a senior software reviewer performing static analysis.

Your job:
Evaluate the proposed code changes.

You must:
- Ensure changes align with the task.
- Ensure minimal modifications.
- Ensure no unrelated logic is removed.
- Detect missing imports.
- Detect obvious runtime risks.
- Detect architectural violations.
- Reject incomplete implementations.

Be strict but fair.

Return structured JSON only.
"""),
    ("user", """
Task:
{task}

Implementation Plan:
{plan}

Existing Files (for updates):
{existing_files}

Proposed Code Changes:
{code_changes}

{format_instructions}
""")
])


def reviewer_node(state: FileAgentState):
    """
    Evaluate generated code using LLM-based reviewer.

    Parameters:
        state (FileAgentState):
            Contains:
                - task (str)
                - file_plan (FilePlan)
                - existing_files (dict)
                - code_change (dict)

    Returns:
        FileAgentState:
            Updated state with:
                - review (dict)

    Behavior:
        - Formats prompt with task, plan, and generated code
        - Sends prompt to LLM
        - Parses structured output into ReviewResult
        - Stores result in state["review"]

    Notes:
        - Acts as quality gate before writing files
        - Ensures correctness and safety
        - Enables automated feedback loop
    """

    logger.info("Executing Reviewer Node")

    # Build prompt with all relevant context
    formatted_prompt = reviewer_prompt.format_messages(
        task=state["task"],  # original task
        plan=["plan"],  # NOTE: currently passing placeholder (likely bug, but unchanged)
        existing_files=state.get("existing_files", {}),  # current file content
        code_changes=state["code_change"],  # generated code
        format_instructions=reviewer_parser.get_format_instructions()  # schema enforcement
    )

    # Call LLM
    response = llm.invoke(formatted_prompt)

    # Parse structured output
    reviewe_result = reviewer_parser.parse(response.content)

    # Store review result in state
    state["review"] = reviewe_result.model_dump()

    logger.info(f"Review by Reviewer Node: \n{reviewe_result.model_dump()}")

    return state


def review_descision(state: FileAgentState):
    """
    Decide next step based on reviewer output.

    Parameters:
        state (FileAgentState):
            Must contain:
                - review (dict)
                - retry_count (dict)

    Returns:
        str:
            One of:
                - "approve" → proceed to writer
                - "revise" → retry coder
                - "abort" → stop execution

    Behavior:
        - If approved → reset retry counter
        - If not approved:
            → increment retry count
            → check retry limit
            → either retry or abort

    Notes:
        - Controls feedback loop between coder and reviewer
        - Prevents infinite retry cycles
    """

    # Check reviewer decision
    if state["review"]["status"].lower() == "approved":
        state["retry_count"]["review"] = 0  # reset retry counter
        return "approve"

    # Increment retry count
    state["retry_count"]["review"] += 1

    # If retry limit exceeded → abort
    if state["retry_count"]["review"] >= MAX_REVIEW_RETRIES:
        return "abort"

    # Otherwise → retry coder
    return "revise"


def writer_node(state: FileAgentState, backup: bool = True):
    """
    Persist code changes to disk safely.

    Args:
        state: AgentState containing code_changes
        backup: wheather to backup overwritten files

    Returns:
        dict:
            Updated state with:
                - written_files (list)
                - code_changes (list)

    Behavior:
        - Validates file path safety (must stay within working_dir)
        - Creates directories if needed
        - Optionally creates backup before overwriting
        - Writes file content to disk

    Notes:
        - Prevents accidental writes outside sandbox
        - Backup helps recover previous file state
    """

    logger.info("Executing Writer Node")

    written_files = []

    # Extract generated code change
    code_change = state.get("code_change")

    # If no changes → skip
    if not code_change:
        logger.warning("No code_change found in the state, skipping writer.")
        return {**state, "written_files": [], "code_changes": []}

    work_dir = state["work_dir"]
    path = code_change["path"]
    content = code_change["content"]
    action = code_change["action"]

    # Safety check: prevent writing outside working directory
    if not path.startswith(work_dir):
        logger.critical(f"skipping the file due to wrong file path: {path}")
        return {**state, "written_files": [], "code_changes": []}

    # Ensure directory exists
    os.makedirs(os.path.dirname(path), exist_ok=True)

    # Backup file before overwrite (only for updates)
    if backup and action == "update" and os.path.exists(path):
        backup_path = path + ".bak"
        shutil.copyfile(path, backup_path)
        logger.debug(f"Backup created: {backup_path}")

    # Write file content
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    # Track written file
    written_files.append(path)

    logger.debug(f"Written Files: \n{written_files}")

    return {
        **state,
        "written_files": [path],
        "code_changes": [code_change]
    }

def static_check_node(state: FileAgentState):
    """
    Perform static code analysis using Ruff on generated files.

    Parameters:
        state (FileAgentState):
            Must contain:
                - written_files (List[str]): files written by writer node
                - retry_count (dict): retry tracking

    Returns:
        dict:
            Updated state with:
                - static_check_success (bool)
                - static_check_output (str)
                - feedback (str | None)
                - retry_count (dict)

    Behavior:
        - If no files were written → skip static analysis
        - Runs `ruff check` on modified files
        - Parses output and determines success/failure
        - Generates feedback if issues are found
        - Updates retry counter for static check loop

    Notes:
        - Ruff is used for fast linting and static validation
        - Feedback is used to guide retries in coder node
        - Prevents infinite loops using retry limits
    """

    logger.info("Executing Static Check Node")

    # Get list of files written during execution
    written_files = state.get("written_files", [])

    # If no files were modified → skip static check
    if not written_files:
        logger.info("No files written, skipping static check.")
        return {
            **state,
            "static_check_success": True,
            "static_check_output": "No files written.",
            "feedback": None
        }

    # Run Ruff linter with JSON output format
    result = subprocess.run(
        ["ruff", "check", "--output-format", "json"] + written_files,
        capture_output=True,
        text=True
    )

    # Determine success based on return code
    success = result.returncode == 0

    # Combine stdout and stderr for full output
    output = result.stdout + result.stderr

    feedback = None

    if not success:
        # Convert Ruff JSON output into readable feedback
        feedback = summarize_ruff_issue(result.stdout)

        # Increment retry counter for static check loop
        retry_count = dict(state.get("retry_count") or {})
        retry_count["static_check_count"] = retry_count.get("static_check_count", 0) + 1

        logger.info(f"Static Check FEEDBACK:\n{feedback}")

    else:
        # No issues → keep retry count unchanged
        retry_count = dict(state.get("retry_count") or {})

    return {
        **state,
        "static_check_success": success,
        "static_check_output": output,
        "feedback": feedback,
        "retry_count": retry_count
    }


def summarize_ruff_issue(json_output: str) -> str:
    """
    Convert Ruff JSON output into human-readable summary.

    Parameters:
        json_output (str):
            Raw JSON string output from Ruff.

    Returns:
        str:
            Formatted summary of issues or fallback message.

    Behavior:
        - Parses JSON output into structured list
        - Extracts:
            - filename
            - line number
            - error code
            - message
        - Formats into readable multi-line string

    Notes:
        - If JSON parsing fails, returns raw output
        - Used to generate feedback for retry loop
    """

    try:
        # Parse JSON output from Ruff
        issues = json.loads(json_output)

        # Build readable issue list
        issue_list = [
            f"{i['filename']}:{i['location']['row']} {i['code']} {i['message']}"
            for i in issues
        ]

        return "Ruff reported:\n" + "\n".join(issue_list)

    except Exception:
        # Fallback if JSON parsing fails
        return "Ruff reported issues but JSON parsing failed:\n" + json_output


def static_check_decision(state: FileAgentState):
    """
    Decide next step based on static analysis results.

    Parameters:
        state (FileAgentState):
            Must contain:
                - static_check_success (bool)
                - retry_count (dict)

    Returns:
        str:
            One of:
                - "pass" → proceed to next stage
                - "retry" → re-run coder with feedback
                - "abort" → stop execution

    Behavior:
        - If static check passes:
            → reset retry counter
            → proceed
        - If fails:
            → increment retry counter
            → retry until limit reached
            → abort if limit exceeded

    Notes:
        - Works together with coder node for iterative improvement
        - Prevents infinite retry loops
    """

    # If static check passed → reset counter and continue
    if state["static_check_success"]:
        state["retry_count"]["static_check_count"] = 0  # reset
        return "pass"

    # Increment retry count
    state["retry_count"]["static_check_count"] += 1

    # Abort if retry limit reached
    if state["retry_count"]["static_check_count"] >= MAX_STATIC_CHECK_RETRIES:
        return "abort"

    # Otherwise → retry code generation
    return "retry"


########## Coder File-Level SUBGRAPH ################

# ================= FILE-LEVEL SUBGRAPH =================

"""
This subgraph handles execution for a SINGLE FILE.

Flow:
    coder → reviewer → (approve/revise/abort) → writer → static_check → (pass/retry/abort)

Purpose:
    - Isolate file-level processing
    - Enable parallel execution (fan-out)
    - Maintain clean retry loops per file
"""

file_workflow = StateGraph(FileAgentState)

# Register nodes for file-level processing
file_workflow.add_node("coder", coder_node)  # Generates code
file_workflow.add_node("reviewer", reviewer_node)  # Reviews code
file_workflow.add_node("writer", writer_node)  # Writes code to disk
file_workflow.add_node("static_check", static_check_node)  # Runs lint/static analysis

# Entry point for subgraph
file_workflow.set_entry_point("coder")

# Define execution flow
file_workflow.add_edge("coder", "reviewer")  # After coding → review

# Conditional routing based on reviewer decision
file_workflow.add_conditional_edges(
    "reviewer",
    review_descision,  # decision function
    {
        "approve": "writer",  # approved → write
        "abort": "writer",    # abort still writes (as per current logic)
        "revise": "coder"     # needs revision → retry coding
    }
)

# After writing → run static checks
file_workflow.add_edge("writer", "static_check")

# Conditional routing after static check
file_workflow.add_conditional_edges(
    "static_check",
    static_check_decision,
    {
        "pass": END,     # success → finish
        "abort": END,    # too many retries → stop
        "retry": "coder" # retry loop → back to coder
    }
)

# Compile subgraph into executable unit
file_subgraph = file_workflow.compile()


# ================= MAIN WORKFLOW GRAPH =================

"""
Main graph orchestrates the entire pipeline across multiple files.

High-level flow:
    setup → file_structure → planner → (reader or skip_reader)
        → fan-out → file_subgraph (parallel per file)
        → fan-in → END

Key Concepts:
    - Fan-out: splits work into per-file subgraphs
    - Fan-in: aggregates results
    - Subgraph: reusable workflow for each file
"""

workflow = StateGraph(AgentState)

# Register main nodes
workflow.add_node("setup", setup_node)  # Initialize execution
workflow.add_node("file_structure", file_structure_node)  # Read repo structure

# Planner with retry policy (auto-retry if failure)
workflow.add_node(
    "planner",
    planner_node,
    retry_policy=RetryPolicy(max_attempts=3)
)

workflow.add_node("reader", reader_node)  # Reads existing files

# Skip node (used when no files need reading)
workflow.add_node("skip_reader", skip_reader_node)

# Subgraph node (compiled file workflow)
workflow.add_node("file_subgraph", file_subgraph)

# Fan-in node to collect results
workflow.add_node("fan_in", fan_in_node)


# Entry point of main graph
workflow.set_entry_point("setup")


# ----------- Define Main Flow -----------

# Setup → read project structure
workflow.add_edge("setup", "file_structure")

# File structure → planning
workflow.add_edge("file_structure", "planner")

# Planner → conditional branch (reader or skip)
workflow.add_conditional_edges("planner", should_read)

# Reader → fan-out (parallel file processing)
workflow.add_conditional_edges("reader", fan_out_edges)

# Skip_reader → fan-out (same behavior, no file reading)
workflow.add_conditional_edges("skip_reader", fan_out_edges)

# Subgraph execution → fan-in aggregation
workflow.add_edge("file_subgraph", "fan_in")

# Final aggregation → END
workflow.add_edge("fan_in", END)


# Compile full workflow graph
graph = workflow.compile()


# ================= GRAPH VISUALIZATION =================

"""
Generate visual representations of the workflow graph.

Outputs:
    - Full graph PNG
    - Main graph only (collapsed subgraph)
    - Expanded graph (with subgraph details)
"""

# Print graph edges for debugging
print(graph.get_graph().edges)

# Generate PNG binary of graph (Mermaid rendering)
png_data = graph.get_graph().draw_mermaid_png()

# Save full graph image
output_file = "python_agent_workflow_graph.png"

with open(output_file, "wb") as f:
    f.write(png_data)

print(f"Graph saved to {output_file}")

# Draw main graph only (subgraph as black box)
graph.get_graph(xray=False).draw_mermaid_png(output_file_path="main_graph.png")

# Draw expanded graph (includes subgraph details)
graph.get_graph(xray=True).draw_mermaid_png(output_file_path="full_graph.png")


# ================= EXECUTION =================

"""
Execute the workflow graph with initial input.

Configuration:
    - recursion_limit: prevents infinite loops

Input:
    - task: user-defined instruction

Output:
    - final AgentState after execution
"""

config = {"recursion_limit": 50}

# Initial input state
input_state = {
    "task": "Write a detailed FastAPI endpoint for CRUD ops for a llm application that can take user input in text of file format"
}

# Execute graph
result = graph.invoke(input_state, config=config)

# Log completion
logger.info("EXECUTION COMPLETED!")

# Print final result
print(result)